<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>soar</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\s*sp\s*{</string>
	<key>foldingStopMarker</key>
	<string>\s*}</string>
	<key>name</key>
	<string>Soar (Raw)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#variable</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Soar comments</string>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\s*(sp)\s*({)\s*([A-z0-9-]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.soar</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.soar</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>production</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>The arrow between the conditions and actions</string>
					<key>match</key>
					<string>--&gt;</string>
					<key>name</key>
					<string>keyword.control.soar</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.soar</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>clause</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variable</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#attribute</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#numeric-constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#other-constant</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.soar</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.character.soar</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Attributes in soar: TODO only last continuation gets colored</string>
			<key>match</key>
			<string>\^([A-z][A-z0-9-]*)(\.([A-z][A-z0-9-]*))*</string>
		</dict>
		<key>numeric-constant</key>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric.soar</string>
		</dict>
		<key>other-constant</key>
		<dict>
			<key>match</key>
			<string>[A-z][A-z0-9-]*</string>
			<key>name</key>
			<string>string.unquoted.soar</string>
		</dict>
		<key>variable</key>
		<dict>
			<key>comment</key>
			<string>Variables in soar conditions or actions</string>
			<key>match</key>
			<string>&lt;[^&gt;]+&gt;</string>
			<key>name</key>
			<string>variable.parameter.soar</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.soar</string>
	<key>uuid</key>
	<string>f29b7345-7106-459d-adfe-d5972b251d8b</string>
</dict>
</plist>
